### ISSUE TITLE
Different accuracies reached with the given code

### ISSUE THREAD

**Issue by SjoerdTimovanVliet** [osmanberke/Deep-SSVEP-BCI#2]
Dear Osman (and others),

I tested the given code without changing anything on the reported datasets of your paper. I reached only maximal 66% on the benchmark dataset and maximal 54% on the BETA dataset. The only difference is that I trained it on my cpu. Could you help me solve this problem? Because I really want to use it for online robotic manipulation for a master-slave system, due to the results reported in your paper.
![trainplot_Bench](https://user-images.githubusercontent.com/27996213/171842877-d870d7b8-f9a9-4d43-8770-946929409864.png)
![trainplot_BETA](https://user-images.githubusercontent.com/27996213/171842879-375a40d6-4f31-466d-99d2-384898996e66.png)
0

**Comment by osmanberke** [comment]
Hello,

Thank you for using our code. We believe you checked the training accuracy of first-stage training, could you also check the testing accuracy of second-stage training via the matrix variable named as "acc_matrix". Also, our reported accuracy is the mean accuracy across subjects, hence for some subjects' testing accuracy could be less than the reported accuracies. We hope this answer helps you. If you have further questions, we will be happy to answer those too.
