### ISSUE TITLE
Possibility to get the pyschtoolbox/matlab code for datacollection and the qwert keyboard

### ISSUE THREAD

**Issue by SjoerdTimovanVliet** [osmanberke/Deep-SSVEP-BCI#3]
Dear Osman(and others),

Thank you for the help earlier. I could reproduce the results of the BETA dataset in matlab, except the chebyfilter. Still gonna work on the filter itself. However, next week I want to start the ssvep datacollection to retrain the model using an OpenBCI headset and use it eventually in online robotic teleoperation. Can I have access to the used datacollection code and the stimulation code created with psychtoolbox? It would greatly help me.

Best regards,

Sjoerd

**Comment by osmanberke** [comment]
Dear Sjoerd,

In the study, we used the publicly available benchmark and BETA datasets. Because of this fact, we did not collect any data. Hence, unfortunately, we do not have any code for data collection. You may try to ask the authors of the datasets. 

King regards,
Osman Berke.

**Comment by SjoerdTimovanVliet** [comment]
Dear Osman,

I see. Thanks for the information and your help.

Best regards,

Sjoerd
